name: Maven CI

on:
  push:
    branches: [ branch-2.2.1 ]
  pull_request:
    branches: [ branch-2.2.1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run install
        run: ./dev/make-distribution.sh --name spark --tgz -Dhadoop.version=2.7.3 -Phive -Phive-thriftserver -Pyarn
      - name: display
        run: ls -lah
      - name: Download a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spark-2.2.1-bin-spark.tgz
          path: spark-2.2.1-bin-spark.tgz

